#!/usr/bin/env perl
# Prints a table of UD languages in MarkDown/HTML.
# Copyright © 2026 Dan Zeman <zeman@ufal.mff.cuni.cz>
# License: GNU GPL

use utf8;
use open ':utf8';
binmode(STDIN, ':utf8');
binmode(STDOUT, ':utf8');
binmode(STDERR, ':utf8');
use YAML qw(LoadFile);
use Getopt::Long;

my $langyaml = 'codes_and_flags.yaml'; # provide path on command line if not in current folder
my $docspath = '../docs';
GetOptions
(
    'codes=s'    => \$langyaml,
    'docs-dir=s' => \$docspath
);

if(! -f $langyaml)
{
    die("Cannot find file '$langyaml'");
}
if(! -d $docspath)
{
    die("Cannot find folder '$docspath'");
}
my $languages = LoadFile($langyaml);
my @languages = sort(keys(%{$languages}));
my $table;
$table .= "<table id=\"langTable\">\n";
$table .= "  <tr>";
$table .= "<th onclick=\"sortTable(0)\">Language</th>";
$table .= "<th onclick=\"sortTable(1)\">ISO Code</th>";
$table .= "<th onclick=\"sortTable(2)\">Family</th>";
$table .= "<th onclick=\"sortTable(3)\">Genus</th>";
$table .= "</tr>\n";
$table .= "  <tr>\n";
$table .= "    <td><input type=\"text\" id=\"fLanguage\" onkeyup=\"filterTable()\" title=\"Type in language name\"></td>\n";
$table .= "    <td></td>\n";
$table .= "    <td></td>\n";
$table .= "    <td></td>\n";
$table .= "  </tr>\n";
foreach my $lname (@languages)
{
    $table .= "  <tr>";
    $table .= "<td>$lname</td>";
    $table .= "<td><tt>$languages->{$lname}{lcode}</tt></td>";
    $table .= "<td>$languages->{$lname}{family}</td>";
    $table .= "<td>$languages->{$lname}{genus}</td>";
    $table .= "</tr>\n";
}
$table .= "</table>\n";
print <<EOF
<!--
  This file is generated by a script. Do not edit it manually.
  Your edits will be overwritten without notice.
-->

<style>
th {
  cursor: pointer;
}
tr:nth-child(even) {
  background-color: lightgray;
}
</style>

$table

<script>
function sortTable(n) {
  var table, rows, switching, i, x, y, shouldSwitch, dir, switchcount = 0;
  table = document.getElementById("langTable");
  switching = true;
  // Set the sorting direction to ascending:
  dir = "asc";
  /* Make a loop that will continue until
  no switching has been done: */
  while (switching) {
    // Start by saying: no switching is done:
    switching = false;
    rows = table.rows;
    /* Loop through all table rows (except the
    first, which contains table headers): */
    for (i = 1; i < (rows.length - 1); i++) {
      // Start by saying there should be no switching:
      shouldSwitch = false;
      /* Get the two elements you want to compare,
      one from current row and one from the next: */
      x = rows[i].getElementsByTagName("TD")[n];
      y = rows[i + 1].getElementsByTagName("TD")[n];
      /* Check if the two rows should switch place,
      based on the direction, asc or desc: */
      if (dir == "asc") {
        if (x.innerHTML.toLowerCase() > y.innerHTML.toLowerCase()) {
          // If so, mark as a switch and break the loop:
          shouldSwitch = true;
          break;
        }
      } else if (dir == "desc") {
        if (x.innerHTML.toLowerCase() < y.innerHTML.toLowerCase()) {
          // If so, mark as a switch and break the loop:
          shouldSwitch = true;
          break;
        }
      }
    }
    if (shouldSwitch) {
      /* If a switch has been marked, make the switch
      and mark that a switch has been done: */
      rows[i].parentNode.insertBefore(rows[i + 1], rows[i]);
      switching = true;
      // Each time a switch is done, increase this count by 1:
      switchcount ++;
    } else {
      /* If no switching has been done AND the direction is "asc",
      set the direction to "desc" and run the while loop again. */
      if (switchcount == 0 && dir == "asc") {
        dir = "desc";
        switching = true;
      }
    }
  }
}

function filterTable() {
  var input, filter, table, tr, td, i, txtValue;
  input = document.getElementById("fLanguage");
  filter = input.value.toUpperCase();
  table = document.getElementById("langTable");
  tr = table.getElementsByTagName("tr");
  for (i = 0; i < tr.length; i++) {
    td = tr[i].getElementsByTagName("td")[0];
    if (td) {
      txtValue = td.textContent || td.innerText;
      if (txtValue.toUpperCase().indexOf(filter) > -1) {
        tr[i].style.display = "";
      } else {
        tr[i].style.display = "none";
      }
    }
  }
}
</script>
EOF
;
