#!/usr/bin/env perl
# Prints a table of UD languages in MarkDown/HTML.
# Copyright © 2026 Dan Zeman <zeman@ufal.mff.cuni.cz>
# License: GNU GPL

use utf8;
use open ':utf8';
binmode(STDIN, ':utf8');
binmode(STDOUT, ':utf8');
binmode(STDERR, ':utf8');
use YAML qw(LoadFile);
use Getopt::Long;

my $langyaml = 'codes_and_flags.yaml'; # provide path on command line if not in current folder
my $docspath = '../docs';
GetOptions
(
    'codes=s'    => \$langyaml,
    'docs-dir=s' => \$docspath
);

if(! -f $langyaml)
{
    die("Cannot find file '$langyaml'");
}
if(! -d $docspath)
{
    die("Cannot find folder '$docspath'");
}
my $languages = LoadFile($langyaml);
my @languages = sort(keys(%{$languages}));
my $table;
$table .= "<table>\n";
$table .= "  <tr><th>Language</th><th>ISO Code</th><th>Family</th><th>Genus</th></tr>\n";
foreach my $lname (@languages)
{
    $table .= "  <tr>";
    $table .= "<td>$lname</td>";
    $table .= "<td><tt>$languages->{$lname}{lcode}</tt></td>";
    $table .= "<td>$languages->{$lname}{family}</td>";
    $table .= "<td>$languages->{$lname}{genus}</td>";
    $table .= "</tr>\n";
}
$table .= "</table>\n";
print <<EOF
<!--
  This file is generated by a script. Do not edit it manually.
  Your edits will be overwritten without notice.
-->

$table

EOF
;
