#!/usr/bin/env perl
# Prints a table of UD languages in MarkDown/HTML.
# Copyright © 2026 Dan Zeman <zeman@ufal.mff.cuni.cz>
# License: GNU GPL

use utf8;
use open ':utf8';
binmode(STDIN, ':utf8');
binmode(STDOUT, ':utf8');
binmode(STDERR, ':utf8');
use YAML qw(LoadFile);
use Getopt::Long;

my $langyaml = 'codes_and_flags.yaml'; # provide path on command line if not in current folder
my $docspath = '../docs';
GetOptions
(
    'codes=s'    => \$langyaml,
    'docs-dir=s' => \$docspath
);

if(! -f $langyaml)
{
    die("Cannot find file '$langyaml'");
}
if(! -d $docspath)
{
    die("Cannot find folder '$docspath'");
}
my $languages = LoadFile($langyaml);
my @languages = sort(keys(%{$languages}));
my $table;
$table .= "<table id=\"langTable\">\n";
$table .= "  <tr>\n";
$table .= "    <th></th>\n";
$table .= "    <th onclick=\"sortTable(0)\">Language</th>\n";
$table .= "    <th onclick=\"sortTable(1)\">ISO Code</th>\n";
$table .= "    <th onclick=\"sortTable(2)\">Family</th>\n";
$table .= "    <th onclick=\"sortTable(3)\">Genus</th>\n";
$table .= "    <th>Documentation</th>\n";
$table .= "  </tr>\n";
$table .= "  <tr>\n";
$table .= "    <th></th>\n";
$table .= "    <th><input size=\"1\" type=\"text\" id=\"fLanguage\" onkeyup=\"filterTable()\" title=\"Type in language name\"></th>\n";
$table .= "    <th><input size=\"1\" type=\"text\" id=\"fCode\" onkeyup=\"filterTable()\" title=\"Type in language code\"></th>\n";
$table .= "    <th><input size=\"1\" type=\"text\" id=\"fFamily\" onkeyup=\"filterTable()\" title=\"Type in family\"></th>\n";
$table .= "    <th><input size=\"1\" type=\"text\" id=\"fGenus\" onkeyup=\"filterTable()\" title=\"Type in genus\"></th>\n";
$table .= "    <th></th>\n";
$table .= "  </tr>\n";
foreach my $lname (@languages)
{
    my $family = $languages->{$lname}{family};
    $family = 'Indo-European' if($family eq 'IE');
    my $genus = $languages->{$lname}{genus};
    $genus = $family if($genus eq '');
    # Does the language have documentation in UD?
    my $langdocfile = "$docspath/_$languages->{$lname}{lcode}/index.md";
    my $langdoclink = '';
    if(-f $langdocfile)
    {
        $langdoclink = "<a href=\"/$languages->{$lname}{lcode}/index.html\">doc</a>";
    }
    $table .= "  <tr>";
    $table .= "<td><img class=\"flag\" src=\"/flags/png/$languages->{$lname}{flag}.png\"></td>";
    $table .= "<td>$lname</td>";
    $table .= "<td><tt>$languages->{$lname}{lcode}</tt></td>";
    $table .= "<td>$family</td>";
    $table .= "<td>$genus</td>";
    $table .= "<td>$langdoclink</td>";
    $table .= "</tr>\n";
}
$table .= "</table>\n";
print <<EOF
<!--
  This file is generated by a script. Do not edit it manually.
  Your edits will be overwritten without notice.
-->

<style>
input {
  width: 95%;
}
th {
  cursor: pointer;
}
tr:nth-child(even) {
  background-color: lightgray;
}
</style>

$table

<script>
function sortTable(n) {
  var table, rows, switching, i, x, y, shouldSwitch, dir, switchcount = 0;
  table = document.getElementById("langTable");
  switching = true;
  // Set the sorting direction to ascending:
  dir = "asc";
  /* Make a loop that will continue until
  no switching has been done: */
  while (switching) {
    // Start by saying: no switching is done:
    switching = false;
    rows = table.rows;
    /* Loop through all table rows (except the
    first, which contains table headers): */
    for (i = 2; i < (rows.length - 1); i++) {
      // Start by saying there should be no switching:
      shouldSwitch = false;
      /* Get the two elements you want to compare,
      one from current row and one from the next: */
      x = rows[i].getElementsByTagName("TD")[n];
      y = rows[i + 1].getElementsByTagName("TD")[n];
      /* Check if the two rows should switch place,
      based on the direction, asc or desc: */
      if (dir == "asc") {
        if (x.innerHTML.toLowerCase() > y.innerHTML.toLowerCase()) {
          // If so, mark as a switch and break the loop:
          shouldSwitch = true;
          break;
        }
      } else if (dir == "desc") {
        if (x.innerHTML.toLowerCase() < y.innerHTML.toLowerCase()) {
          // If so, mark as a switch and break the loop:
          shouldSwitch = true;
          break;
        }
      }
    }
    if (shouldSwitch) {
      /* If a switch has been marked, make the switch
      and mark that a switch has been done: */
      rows[i].parentNode.insertBefore(rows[i + 1], rows[i]);
      switching = true;
      // Each time a switch is done, increase this count by 1:
      switchcount ++;
    } else {
      /* If no switching has been done AND the direction is "asc",
      set the direction to "desc" and run the while loop again. */
      if (switchcount == 0 && dir == "asc") {
        dir = "desc";
        switching = true;
      }
    }
  }
}

function filterTable() {
  var fl, fc, ff, fg, table, tr;
  fl = document.getElementById("fLanguage").value.toUpperCase();
  fc = document.getElementById("fCode").value.toUpperCase();
  ff = document.getElementById("fFamily").value.toUpperCase();
  fg = document.getElementById("fGenus").value.toUpperCase();
  table = document.getElementById("langTable");
  tr = table.getElementsByTagName("tr");
  for (i = 0; i < tr.length; i++) {
    if (matchRow(tr[i], fl, fc, ff, fg)) {
      tr[i].style.display = "";
    } else {
      tr[i].style.display = "none";
    }
  }
}

function matchRow(tr, fl, fc, ff, fg) {
  var match, td, txtValue;
  match = true;
  if (fl) {
    td = tr.getElementsByTagName("td")[0];
    if (td) {
      txtValue = td.textContent || td.innerText;
      match = match && txtValue.toUpperCase().indexOf(fl) > -1;
    }
  }
  if (fc) {
    td = tr.getElementsByTagName("td")[1];
    if (td) {
      txtValue = td.textContent || td.innerText;
      match = match && txtValue.toUpperCase().indexOf(fc) > -1;
    }
  }
  if (ff) {
    td = tr.getElementsByTagName("td")[2];
    if (td) {
      txtValue = td.textContent || td.innerText;
      match = match && txtValue.toUpperCase().indexOf(ff) > -1;
    }
  }
  if (fg) {
    td = tr.getElementsByTagName("td")[3];
    if (td) {
      txtValue = td.textContent || td.innerText;
      match = match && txtValue.toUpperCase().indexOf(fg) > -1;
    }
  }
  return match;
}
</script>
EOF
;
